services:
  fsw:
    stop_grace_period: 3s
    user: user
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - HOST_UID=${HOST_UID:-1000}
          - HOST_GID=${HOST_GID:-1000}
          - progress=plain
    image: $FSW_IMG
    working_dir: ${FSW_WDIR}
    environment:
        - GEVENT_SUPPORT=True
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
        - UPLINK_TARGET_PORT=$UPLINK_TARGET_PORT
        - FPRIME_CONFIG_DIR=/fsw/config
    volumes:
      - ${SCRIPT_DIR}:${FSW_WDIR}
    ports:
      - "${GDB_PORT}:${GDB_PORT}"
      - $DOWNLINK_TARGET_PORT:50050
      - $GDS_WEB_GUI_PORT:5000
    network_mode: host
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE
      # For gdbserver's addr space randomization
      - SYS_PTRACE
    ulimits:
      rtprio: 99
    healthcheck:
      test: ["CMD-SHELL", "pgrep FlightComputer"]
      interval: 2s
      timeout: 3s
      retries: 25
      start_period: 5s

  # extended service that leverages a host device
  fsw-with-device:
      extends: fsw
      devices:
        - "${DEVICE_PORT}:/dev/${CONTAINER_PORT}"
      # Add the dialout group to ensure access permissions
      group_add:
        - "dialout"
